version: '3.8'

volumes:
  db-volume:

x-backend: &backend
  build:
    context: .
    dockerfile: _docker/backend/Dockerfile
  image: backend
  volumes:
    - ./backend:/backend
    - /backend/node_modules
  restart: unless-stopped
  env_file: .env



x-frontend: &frontend
  build:
    context: .
    dockerfile: _docker/frontend/Dockerfile
  image: frontend
  volumes:
    - ./frontend:/frontend
    - /frontend/node_modules

services:
  backend:
    <<: *backend
    command: npm run start
    ports:
      - 8080:8080
  frontend:
    <<: *frontend
    command: npm run start
    ports:
    - 3000:3000